---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
  annotations:
    backstage.io/owner: guests
    backstage.io/managed-by-location: url:https://github.com/your-org/your-repo/catalog-info.yaml
    # Update this to your actual Jenkins job path
    jenkins.io/job-full-name: LoginCheck
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bff-publisher
  annotations:
    backstage.io/owner: guests
    backstage.io/techdocs-ref: url:https://github.com/tunghauvan-interspace/backstage/tree/master/examples/example-docs
    backstage.io/source-location: url:https://github.com/interspace-obs/bff-publisher
    # Add Jenkins annotation to the component as well if needed
    jenkins.io/job-full-name: "DEV_BFFPublisher"
    sonarqube.org/project-key: "interspace-obs-sonarqube/bff-publisher"
  links:
  - url: https://grafana.asean-accesstrade.net/
    title: My Dashboard
    icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-rest-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: bff-publisher-rest-api
  annotations:
    backstage.io/owner: guests
    backstage.io/api-docs: url:https://example.com/openapi.yaml
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    openapi: 3.0.0
    info:
      title: Example REST API
      version: '1.0.0'
      description: A simple REST API example
    paths:
      /examples:
        get:
          summary: Get examples
          responses:
            '200':
              description: Successful response
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/Example'
        post:
          summary: Create example
          requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Example'
          responses:
            '201':
              description: Example created
    components:
      schemas:
        Example:
          type: object
          properties:
            example:
              type: string